name: git-azcopy-snap
version: '1.00'
summary: This is snap that makes available git and AZCopy
description: |
  snap for Ubuntu Core 16.04 that will allow usage of the following utilities   git
  AZCopy
grade: devel
confinement: devmode

apps:
  azcopy:
    command: /usr/bin/azcopy
  git:
    command: /usr/bin/git
    plugs:
      - network

parts:
  ms-azcopy:
    source: https://aka.ms/downloadazcopylinux64
    plugin: dump
    source-type: tar
    override-stage: |
      snapcraftctl stage
      sudo sed -i 's|/usr/bin|$SNAP/usr/bin|g' install.sh
#      snapcraftctl build      
#      sudo sed -i 's|/usr/bin|$SNAP/usr/bin|g' $SNAPCRAFT_PART_INSTALL/install.sh
  scm-git:
    source: https://github.com/git/git.git
#    source: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.7.4.tar.gz
    plugin: autotools
    source-type: git
    source-tag: v2.17.1
    source-depth: 1
    build-packages: 
      - dh-autoreconf
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - asciidoc
      - xmlto
      - docbook2x
#    configflags: ["--prefix=/usr"]
