name: git-azcopy-snap # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: This is snap that makes available git and AZCopy # 79 char long summary
description: |
  snap for Ubuntu Core 16.04 that will allow usage of the following utilities:  git
  AZCopy

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
